FROM ubuntu:24.04

RUN apt-get update \
    && apt-get install -y --no-install-recommends openscad xvfb \
    && rm -rf /var/lib/apt/lists/*

ENV OPENSCADPATH=/work/libraries

WORKDIR /work

ENTRYPOINT ["xvfb-run", "--auto-servernum", "openscad"]
